###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      build: phpdocker/mysql
      container_name: hotcrp-mysql
      working_dir: /application
      volumes:
        - .:/application
      command: --max_allowed_packet=104857600      # Set max_allowed_packet to 256M (or any other value)
      environment:
        - MYSQL_ROOT_PASSWORD=rootpwd
        - MYSQL_DATABASE=hotcrp
        - MYSQL_USER=hotcrp
        - MYSQL_PASSWORD=hotcrppwd
      ports:
        - "9002:3306"
      hostname: hotcrp-mysql
      restart: on-failure

    webserver:
      #image: nginx:alpine
      build: phpdocker/nginx
      container_name: hotcrp-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"
      hostname: hotcrp-webserver
      links: 
        - mysql
      restart: on-failure
      #expose:
      # - "80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: hotcrp-php-fpm
      working_dir: /application
      depends_on:
        - mysql
      #ports:
      #  - "9000:9000"
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      hostname: hotcrp-php-fpm
      domainname: localhost.localdomain
      restart: on-failure

